kind = "mobile"
previewPath = "/mobile/"
title = "Jarida Mobile"
version = "1.0.0"
id = "artifacts/jarida-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24566

[services.development]
run = "pnpm --filter @workspace/jarida-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jarida-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/jarida-mobile", "run", "serve" ]

[services.env]
PORT = "24566"
BASE_PATH = "/mobile/"
